=== corecodeio/entry-challenge-v1/src/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "examples": [{
        "contactInfo": {
            "fullName": "Gus",
            "emailAddress": "gustavoandresibarra@gmail.com"
        },
        "github": {
            "profileURL": "",
            "username": ""
        },
        "credentials": {
            "password": "password"
        },
        "personalInfo": {
            "questions": [{
                    "question": "If I was a Sr. Programmer, I would like to build:",
                    "answer": "..."
                },
                {
                    "question": "Por favor indica el URL que me lleva a la línea de código de la definición de React.useEffect",
                    "answer": "..."
                },
                {
                    "question": "code is poetry, because:",
                    "answer": ""
                }
            ]
        }
    }],
    "required": [
        "contactInfo",
        "github",
        "credentials",
        "personalInfo"
    ],
    "additionalProperties": true,
    "properties": {
        "contactInfo": {
            "$id": "#/properties/contactInfo",
            "type": "object",
            "title": "The contactInfo schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [{
                "fullName": "Gus",
                "emailAddress": "gustavoandresibarra@gmail.com"
            }],
            "required": [
                "fullName",
                "emailAddress"
            ],
            "additionalProperties": true,
            "properties": {
                "fullName": {
                    "$id": "#/properties/contactInfo/properties/fullName",
                    "type": "string",
                    "title": "The fullName schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "Gus"
                    ]
                },
                "emailAddress": {
                    "$id": "#/properties/contactInfo/properties/emailAddress",
                    "type": "string",
                    "title": "The emailAddress schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "gustavoandresibarra@gmail.com"
                    ]
                }
            }
        },
        "github": {
            "$id": "#/properties/github",
            "type": "object",
            "title": "The github schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [{
                "profileURL": "",
                "username": ""
            }],
            "required": [
                "profileURL",
                "username"
            ],
            "additionalProperties": true,
            "properties": {
                "profileURL": {
                    "$id": "#/properties/github/properties/profileURL",
                    "type": "string",
                    "title": "The profileURL schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        ""
                    ]
                },
                "username": {
                    "$id": "#/properties/github/properties/username",
                    "type": "string",
                    "title": "The username schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        ""
                    ]
                }
            }
        },
        "credentials": {
            "$id": "#/properties/credentials",
            "type": "object",
            "title": "The credentials schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [{
                "password": "password"
            }],
            "required": [
                "password"
            ],
            "additionalProperties": true,
            "properties": {
                "password": {
                    "$id": "#/properties/credentials/properties/password",
                    "type": "string",
                    "title": "The password schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "password"
                    ]
                }
            }
        },
        "personalInfo": {
            "$id": "#/properties/personalInfo",
            "type": "object",
            "title": "The personalInfo schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [{
                "questions": [{
                        "question": "If I was a Sr. Programmer, I would like to build:",
                        "answer": "..."
                    },
                    {
                        "question": "Por favor indica el URL que me lleva a la línea de código de la definición de React.useEffect",
                        "answer": "..."
                    },
                    {
                        "question": "code is poetry, because:",
                        "answer": ""
                    }
                ]
            }],
            "required": [
                "questions"
            ],
            "additionalProperties": true,
            "properties": {
                "questions": {
                    "$id": "#/properties/personalInfo/properties/questions",
                    "type": "array",
                    "title": "The questions schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": [],
                    "examples": [
                        [{
                                "question": "If I was a Sr. Programmer, I would like to build:",
                                "answer": "..."
                            },
                            {
                                "question": "Por favor indica el URL que me lleva a la línea de código de la definición de React.useEffect",
                                "answer": "..."
                            }
                        ]
                    ],
                    "additionalItems": true,
                    "items": {
                        "anyOf": [{
                            "$id": "#/properties/personalInfo/properties/questions/items/anyOf/0",
                            "type": "object",
                            "title": "The first anyOf schema",
                            "description": "An explanation about the purpose of this instance.",
                            "default": {},
                            "examples": [{
                                "question": "If I was a Sr. Programmer, I would like to build:",
                                "answer": "..."
                            }],
                            "required": [
                                "question",
                                "answer"
                            ],
                            "additionalProperties": true,
                            "properties": {
                                "question": {
                                    "$id": "#/properties/personalInfo/properties/questions/items/anyOf/0/properties/question",
                                    "type": "string",
                                    "title": "The question schema",
                                    "description": "An explanation about the purpose of this instance.",
                                    "default": "",
                                    "examples": [
                                        "If I was a Sr. Programmer, I would like to build:"
                                    ]
                                },
                                "answer": {
                                    "$id": "#/properties/personalInfo/properties/questions/items/anyOf/0/properties/answer",
                                    "type": "string",
                                    "title": "The answer schema",
                                    "description": "An explanation about the purpose of this instance.",
                                    "default": "",
                                    "examples": [
                                        "..."
                                    ]
                                }
                            }
                        }],
                        "$id": "#/properties/personalInfo/properties/questions/items"
                    }
                }
            }
        }
    }
}

=== corecodeio/entry-challenge-v1/src/profile.json
{
    "contactInfo": {
        "fullName": "Luis Abel Pozuelos Juarez",
        "emailAddress": "lpozuelos@irc.com.gt"
    },
    "github": {
        "profileURL": "https://github.com/blindlp",
        "username": "blindlp"
    },
    "credentials": {
        "password": ""
    },
    "personalInfo": {
        "questions": [
            {
                "question": "If I was a Sr. Programmer, I would like to build:",
                "answer": "I create new application to bring more easily to solve problems in my field,sharing my knowledge  and I trying to find new opportunities to develop business and create new sources of work."
            },
            {
                "question": "Por favor indica el URL que me lleva a la línea de código de la definición de React.useEffect",
                "answer": "https://es.reactjs.org/docs/hooks-reference.html#useeffect "
            },
            {
                "question": "code is poetry, because:",
                "answer": "it's poetry because you need to have different feelings to create and develop your abilities, I think is a king of art the way we express our code because its unique everybody has his own style"
            }
        ]
    }
}

=== corecodeio/entry-challenge-v1/src/data.json
{
    "contactInfo": {
        "fullName": "Isaias Samuel Puga Solares",
        "emailAddress": "puga.isaias@gmail.com"
    },
    "github": {
        "profileURL": "https://github.com/pugaIsaias",
        "username": "pugaIsaias"
    },
    "credentials": {
        "password": "4MXw5kW9"
    },
    "personalInfo": {
        "questions": [
            {
                "question": "If I was a Sr. Programmer, I would like to build:",
                "answer": "Respuesta: Develop games, and good experiences"
            },
            {
                "question":
                "Por favor indica el URL que me lleva a la línea de código de la definición de React.useEffect",
                "answer": "Respuesta: ..."
            },
            {
                "question": "code is poetry, because:",
                "answer": "Respuesta: It has free form, can be fun, or tragic. And with words you build something that can be enjoyed by yourself, or others."
            }
        ]
    }
}

=== corecodeio/entry-challenge-v1/src/datos.json
{
    "contactInfo": {
        "fullName": "Jose Eduardo Lopez Gonzalez",
        "emailAddress": "jeduardo14lopez@gmail.com"
    },
    "github": {
        "profileURL": "https://github.com/jelg14",
        "username": "jelg14"
    },
    "credentials": {
        "password": "asdf"
    },
    "personalInfo": {
        "questions": [{
                "question": "If I was a Sr. Programmer, I would like to build:",
                "answer": "If I was a S. Programmer, I would like to create a technology that could change the world"
            },
            {
                "question": "Por favor indica el URL que me lleva a la línea de código de la definición de React.useEffect",
                "answer": "Respuesta:https://github.com/facebook/react/blob/655affa302437208e6f03c9ca6d170ea1707ace3/packages/react-reconciler/src/ReactFiberHooks.new.js#L1878"
            },
            {
                "question": "code is poetry, because:",
                "answer": "code is poetry because with it you can create anything you can imagine"
            }
        ]
    }
}

=== corecodeio/entry-challenge-v1/sendedInfo.json
{
  "contactInfo": {
    "fullName": "",
    "emailAddress": ""
  },
  "github": {
    "profileURL": "",
    "username": ""
  },
  "credentials": {
    "password": "Cambia esta contraseña a una que sólo tú sepas"
  },
  "personalInfo": {
    "questions": [
      {
        "question": "If I was a Sr. Programmer, I would like to build:",
        "answer": "Respuesta: ..."
      },
      {
        "question": "Por favor indica el URL que me lleva a la línea de código de la definición de React.useEffect",
        "answer": "Respuesta: ..."
      },
      {
        "question": "code is poetry, because:",
        "answer": "Respuesta: ..."
      }
    ]
  }
}
